language: rust
rust:
- nightly
- stable
before_script:
- if [ $TRAVIS_RUST_VERSION == nightly ]; then cargo install clippy --git https://github.com/rust-lang-nursery/rust-clippy.git --force; fi
script:
- cargo build
- if [ $TRAVIS_RUST_VERSION == nightly ]; then cargo test -- --nocapture ; fi
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master
notifications:
    email:
      on_success: never
