[package]
authors = ["Pascal Hertleif <killercup@gmail.com>"]
license = "Apache-2.0/MIT"
name = "rustfix"
readme = "README.md"
version = "0.1.0"

[dependencies]
clap = "2.9.2"
colored = "1.2.0"
quick-error = "1.1.0"
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"
