[package]
name = "rustfix"
version = "0.6.1"
authors = [
    "Pascal Hertleif <killercup@gmail.com>",
    "Oliver Schneider <oli-obk@users.noreply.github.com>",
]
rust-version = "1.70.0"  # MSRV:3
edition.workspace = true
license.workspace = true
homepage = "https://github.com/rust-lang/cargo"
repository = "https://github.com/rust-lang/cargo"
description = "Automatically apply the suggestions made by rustc"
documentation = "https://docs.rs/rustfix"
exclude = [
    "examples/*",
    "tests/*",
]

[dependencies]
anyhow.workspace = true
log = "0.4.1"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
duct = "0.9"
env_logger = "0.5.0-rc.1"
log = "0.4.1"
proptest = "0.7.0"
similar = "0.4.0"
tempfile.workspace = true

[lints]
workspace = true
